#!/bin/sh

if test $# -lt 2; then
  printf '%s\n' "Usage: cg <input> <format> [rg-argument…]" > /dev/stderr
  exit 1
fi

input=$1 format=$2
shift 2
regex=$(chronic --input "$input" "$format" --format '(%s)' --separator '|')
rg "$regex" "$@"
